id = "noctis"
name = "Noctis Blured/Opaque"
version = "0.1.0"
schema_version = 1
authors = ["mintzic"]
description = "Original Noctis ported to zed with blured/Opaque"
repository = "https://github.com/mintzic/noctis-blured"
